name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
        working-directory: onlypans

      - name: Create and migrate database
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/test_db
          SECRET_KEY_BASE: hardcodeedbullshit
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
        working-directory: onlypans

      - name: Run RSpec tests
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/test_db
          SECRET_KEY_BASE: hardcodeedbullshit
        run: bundle exec rspec
        working-directory: onlypans